version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: code-deploy/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
      - location: code-deploy/start_server
        timeout: 300
        runas: root
  ApplicationStop:
    - location: code-deploy/stop_server
      timeout: 300
      runas: root

