version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: code-deploy/clean
      timeout: 300
      runas: ec2-user
    - location: code-deploy/install_dependencies
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: code-deploy/start_server
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: code-deploy/stop_server
      timeout: 300
      runas: ec2-user

